from setuptools import setup, find_packages
from codecs import open
from contextlib import contextmanager

from setuptools.command.sdist import sdist as _sdist
from setuptools.command.test import test as _test

NAME = 'garasu_model'
DESC = 'SQLAlchemy base model for pyramid'
AUTHOR = 'Nanang Suryadi'
AUTHOR_EMAIL = 'nanang.ask@gmail.com'
URL = 'https://github.com/suryakencana/garasu_model.git'
LICENSE = 'GNU GPL License'
KEYWORDS = ['model', 'SQLAlchemy', 'pyramid']
CLASSIFIERS = [
    'Development Status :: 4 - Beta',
    'Environment :: Console',
    'Environment :: Web Environment',
    'Framework :: Pyramid',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: BSD License',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 2.7. 3.4+',
]
INSTALL_REQUIRES = [
    'zope.sqlalchemy',
    'SQLAlchemy',
    'pyramid',
    'pyramid_tm',
    'sqlalchemy_utils',
    'awesome-slugify',
    'python-dateutil',
    'bcrypt',
    'transaction'
]
EXTRAS_REQUIRE = {
    'dev': ['check-manifest'],
    'test': ['coverage'],
}
ENTRY_POINTS = """\
      """

with open('README.rst', encoding='utf-8') as fp:
    LONGDESC = fp.read()


VERSION = __import__('garasu_model').__version__
VERSION_FILE = 'garasu_model/_version.py'
VERSION_TPL = ("# This version file is autogenerated from Git data.\n"
               "def get_version():\n"
               "    return '{version}'\n")


@contextmanager
def static_version_file():
    with open(VERSION_FILE) as fp:
        previous = fp.read()
    with open(VERSION_FILE, 'w') as fp:
        fp.write(VERSION_TPL.format(version=VERSION))
    print('updated {} with version {}'.format(VERSION_FILE, VERSION))
    yield
    with open(VERSION_FILE, 'w') as fp:
        fp.write(previous)
    print('replaced original {}'.format(VERSION_FILE))


class sdist(_sdist):
    def run(self):
        with static_version_file():
            return _sdist.run(self)


class test(_test):
    def run(self):
        print('please run tox instead')


setup(name=NAME,
      version=VERSION,
      description=DESC,
      long_description=LONGDESC,
      classifiers=CLASSIFIERS,
      keywords=KEYWORDS,
      author=AUTHOR,
      author_email=AUTHOR_EMAIL,
      url=URL,
      license=LICENSE,
      include_package_data=True,
      install_requires=INSTALL_REQUIRES,
      extras_require=EXTRAS_REQUIRE,
      entry_points=ENTRY_POINTS,
      cmdclass={'sdist': sdist,
                'test': test},
      packages=find_packages(include=['garasu_model', 'garasu_model.*']),
      zip_safe=False)
